In [2]:
import pandas as pd
import os
import time
import requests

In [3]:
istat_csv = 'istat_dataset.csv'
url = 'https://esploradati.istat.it/SDMXWS/rest/data/41_983'
headers =  {'Accept': 'application/vnd.sdmx.data+csv;version=1.0.0'}
if os.path.exists(istat_csv):
    istat_df = pd.read_csv(istat_csv, dtype={"REF_AREA": str})
else:
    counter= 0 
    while counter < 5:
        try:
            response = requests.get(url, headers=headers)
            response.raise_for_status()
            with open(istat_csv, 'w', encoding='utf-8') as file:
                file.write(response.text)
            istat_df = pd.read_csv(istat_csv, dtype={"REF_AREA": str})
            print(f"Data saved to {istat_csv}")
            break
        except requests.exceptions.RequestException as error:
            print(f"Error: {error}")
            counter = counter + 1
            time.sleep(20)
            if counter == 5:
                raise Exception("Fetching data failed")

In [4]:
istat_df.shape

(573552, 16)

In [158]:
istat_df.sample(5)

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
558647,IT1:41_983(1.0),A,103015,KILLINJ,F,2024,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
541525,IT1:41_983(1.0),A,097032,KILLINJ,F,2011,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98882,IT1:41_983(1.0),A,012040,ROADACC,9,2021,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
332934,IT1:41_983(1.0),A,056004,ROADACC,9,2004,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
563106,IT1:41_983(1.0),A,104003,KILLINJ,F,2006,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
istat_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 573552 entries, 0 to 573551
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DATAFLOW          573552 non-null  str
 1   FREQ              573552 non-null  str
 2   REF_AREA          573552 non-null  str
 3   DATA_TYPE         573552 non-null  str
 4   RESULT            573552 non-null  str
 5   TIME_PERIOD       573552 non-null  int64
 6   OBS_VALUE         573552 non-null  int64
 7   OBS_STATUS        0 non-null       float64
 8   NOTE_DS           0 non-null       float64
 9   NOTE_REF_AREA     0 non-null       float64
 10  NOTE_DATA_TYPE    0 non-null       float64
 11  NOTE_RESULT       0 non-null       float64
 12  NOTE_TIME_PERIOD  0 non-null       float64
 13  BASE_PER          0 non-null       float64
 14  UNIT_MEAS         0 non-null       float64
 15  UNIT_MULT         0 non-null       float64
dtypes: float64(9), int64(2), str(5)
memory usage: 70.0 MB

In [7]:
istat_df['TIME_PERIOD'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023, 2024])

In [26]:
df_list = []
csv_files= ['situas_2018.csv', 'situas_2019.csv', 'situas_2020.csv', 'situas_2021.csv', 'situas_2022.csv', 'situas_2023.csv', 'situas_2024.csv']
for file in csv_files:
    df_list.append(pd.read_csv(file, sep =';', decimal =',', dtype={"Codice Comune (alfanumerico)": str}))
situas_df = pd.concat(df_list, ignore_index=True)
situas_df['Superficie (Kmq)'] = situas_df['Superficie (Kmq)'].str.replace('.', '', regex=False).str.replace(',', '.', regex=False).astype(float)
situas_df.to_csv("situas_dataset.csv", index=False)
situas_df.sample(5)

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
25207,1,3,12,12,012098,12098,Marnate,NaN,VA,0,0,8032,2021,4.8464,2021,8032,2021
42180,1,3,20,20,020027,20027,Gonzaga,NaN,MN,0,0,8663,2021,49.8827,2023,8698,2023
22200,4,18,78,78,078136,78136,Saracena,NaN,CS,0,0,3964,2011,109.1501,2020,3480,2020
13470,4,13,66,66,066073,66073,Poggio Picenze,NaN,AQ,0,0,1068,2011,11.4565,2019,1060,2019
20532,3,12,58,258,058026,58026,Cave,NaN,RM,0,0,10421,2011,17.8793,2020,10728,2020

In [32]:
situas_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55375 entries, 0 to 55374
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  55375 non-null  int64
 1   Codice Regione                  55375 non-null  int64
 2   Codice Provincia (Storico)      55375 non-null  int64
 3   Codice Provincia/Uts            55375 non-null  int64
 4   Codice Comune (alfanumerico)    55375 non-null  str
 5   Codice Comune (numerico)        55375 non-null  int64
 6   Comune                          55368 non-null  str
 7   Comune (dizione straniera)      868 non-null    str
 8   Sigla automobilistica           54731 non-null  str
 9   Capoluogo di Provincia/Uts      55375 non-null  int64
 10  Capoluogo di Regione            55375 non-null  int64
 11  Popolazione legale              55375 non-null  int64
 12  Anno Censimento                 55375 non-null  int64
 13  Superficie (Kmq)                55375 non-null  float64
 14  Anno (Superficie)               55375 non-null  int64
 15  Popolazione residente           55375 non-null  int64
 16  Anno (Popolazione residente)    55375 non-null  int64
dtypes: float64(1), int64(12), str(4)
memory usage: 7.2 MB

In [33]:
situas_df['Superficie (Kmq)'].dtype

dtype('float64')

In [25]:
situas_df['Superficie (Kmq)'].unique()

array([13.1462, 15.7393, 46.3315, ..., 23.6116, 82.4354, 26.8906],
      shape=(12534,))

In [12]:
situas_df['Codice Comune (alfanumerico)'].head()

0    001001
1    001002
2    001003
3    001004
4    001005
Name: Codice Comune (alfanumerico), dtype: str

In [13]:
istat_df['REF_AREA'].head()

0    001001
1    001001
2    001001
3    001001
4    001001
Name: REF_AREA, dtype: str

In [ ]:
# Exploring the possible values of DATA_TYPE column to understand its meaning
istat_df['DATA_TYPE'].unique()

<StringArray>
['KILLINJ', 'ROADACC']
Length: 2, dtype: str

In [144]:
# Checking basic statistics of OBS_VALUE columns to confirm that it is actually a count
istat_df['OBS_VALUE'].describe()

count    573552.000000
mean         20.207603
std         245.813966
min           0.000000
25%           0.000000
50%           1.000000
75%           8.000000
max       30254.000000
Name: OBS_VALUE, dtype: float64

In [ ]:
# Checking the unit of measurement to confirm OBS_VALUE represents counts
istat_df['UNIT_MEAS'].unique()

array([nan])

In [ ]:
# Checking the unit multiplier
#Both UNIT_MEAS and UNIT_MULT are NaN, so OBS_VALUE represents counts
istat_df['UNIT_MULT'].unique()

array([nan])

In [142]:
# Check which distinct codes exist in the RESULT column
istat_df['RESULT'].unique()

<StringArray>
['F', 'M', '9']
Length: 3, dtype: str

In [ ]:
# Verifying KILLINJ data for a single municipality/year: 

df_killinj_test = istat_df[(istat_df['DATA_TYPE'] == 'KILLINJ') & (istat_df['TIME_PERIOD'] == 2019) & (istat_df['REF_AREA'] == '001001')]
print(df_killinj_test[['RESULT', 'OBS_VALUE']])

   RESULT  OBS_VALUE
18      F          5
42      M          0

In [ ]:
# Confirming that across all municipalities KILLINJ only contain F (injured) or M (killed)
f_m_result = istat_df[(istat_df['DATA_TYPE'] == 'KILLINJ') & (istat_df['TIME_PERIOD'] == 2019)].groupby('REF_AREA')['RESULT'].unique()
print(f_m_result)

REF_AREA
001001    [F, M]
001002    [F, M]
001003    [F, M]
001004    [F, M]
001006    [F, M]
           ...
111103    [F, M]
111104    [F, M]
111105    [F, M]
111106    [F, M]
111107    [F, M]
Name: RESULT, Length: 7915, dtype: object

In [ ]:
# Verifying ROADACC data for a single municipality/year: 

df_roadacc_test = istat_df[(istat_df['DATA_TYPE'] == 'ROADACC') & (istat_df['TIME_PERIOD'] == 2019) & (istat_df['REF_AREA'] == '001001')]
print(df_roadacc_test [['RESULT', 'OBS_VALUE']])

   RESULT  OBS_VALUE
66      9          3

In [ ]:
#Confirming that across all municipalities ROADACC is always 9 
nine_values = istat_df[(istat_df['DATA_TYPE'] == 'ROADACC') & (istat_df['TIME_PERIOD'] == 2019)].groupby('REF_AREA')['RESULT'].unique()
print(nine_values)

REF_AREA
001001    [9]
001002    [9]
001003    [9]
001004    [9]
001006    [9]
         ...
111103    [9]
111104    [9]
111105    [9]
111106    [9]
111107    [9]
Name: RESULT, Length: 7915, dtype: object

##  OBS_VALUE, RESULT AND DATA_TYPE


**OBS_VALUE** was confirmed to be a numeric count (of injured, killed people or road accidents) based on:
-  dtype being `int64` (confirmed via `.info()`), meaning whole numbers with no decimals 
- `.describe()` showing whole numbers with and a reasonable range and no decimals (except for mean and std which is expected)
- `UNIT_MEAS` and `UNIT_MULT` both being NaN, meaning no unit conversion or
  scaling is needed before summing the values

This confirms that `OBS_VALUE` can be directly summed or compared across rows

**RESULT** was confirmed thanks to the official ISTAT codelist (CL_ESITO), available at:
`https://esploradati.istat.it/SDMXWS/rest/codelist/IT1/CL_ESITO`

- **M** = "killed" — not male gender (as initially assumed)
- **F** = "injured" — not female gender (as initially assumed)
- **9** = "total"

This explains why:
- **KILLINJ** (killed and injured) only shows M and F, never 9 so the total number of injured and killed people must be calculated by summing F+M manually
- **ROADACC** (road accidents) only shows 9, since a road accident is a single event and doesn't split into killed/injured like KILLINJ does