In [26]:
import pandas as pd
import os
import time
import requests

In [27]:
istat_csv = 'istat_dataset.csv'
url = 'https://esploradati.istat.it/SDMXWS/rest/data/41_983'
headers =  {'Accept': 'application/vnd.sdmx.data+csv;version=1.0.0'}
if os.path.exists(istat_csv):
    istat_df = pd.read_csv(istat_csv, dtype={"REF_AREA": str})
else:
    counter= 0 
    while counter < 5:
        try:
            response = requests.get(url, headers=headers)
            response.raise_for_status()
            with open(istat_csv, 'w', encoding='utf-8') as file:
                file.write(response.text)
            istat_df = pd.read_csv(istat_csv, dtype={"REF_AREA": str})
            print(f"Data saved to {istat_csv}")
            break
        except requests.exceptions.RequestException as error:
            print(f"Error: {error}")
            counter = counter + 1
            time.sleep(20)
            if counter == 5:
                raise Exception("Fetching data failed")

In [28]:
istat_df.shape

(573552, 16)

In [29]:
istat_df.sample(5)

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
327288,IT1:41_983(1.0),A,054017,ROADACC,9,2010,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466843,IT1:41_983(1.0),A,079056,KILLINJ,F,2002,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140586,IT1:41_983(1.0),A,016098,KILLINJ,F,2022,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26882,IT1:41_983(1.0),A,002118,KILLINJ,M,2015,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
420838,IT1:41_983(1.0),A,070003,KILLINJ,M,2017,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
istat_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 573552 entries, 0 to 573551
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DATAFLOW          573552 non-null  str
 1   FREQ              573552 non-null  str
 2   REF_AREA          573552 non-null  str
 3   DATA_TYPE         573552 non-null  str
 4   RESULT            573552 non-null  str
 5   TIME_PERIOD       573552 non-null  int64
 6   OBS_VALUE         573552 non-null  int64
 7   OBS_STATUS        0 non-null       float64
 8   NOTE_DS           0 non-null       float64
 9   NOTE_REF_AREA     0 non-null       float64
 10  NOTE_DATA_TYPE    0 non-null       float64
 11  NOTE_RESULT       0 non-null       float64
 12  NOTE_TIME_PERIOD  0 non-null       float64
 13  BASE_PER          0 non-null       float64
 14  UNIT_MEAS         0 non-null       float64
 15  UNIT_MULT         0 non-null       float64
dtypes: float64(9), int64(2), str(5)
memory usage: 70.0 MB

In [31]:
istat_df['TIME_PERIOD'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023, 2024])

In [35]:
df_list = []
csv_files= ['situas_2018.csv', 'situas_2019.csv', 'situas_2020.csv', 'situas_2021.csv', 'situas_2022.csv', 'situas_2023.csv', 'situas_2024.csv']
for file in csv_files:
    df_list.append(pd.read_csv(file, sep=';', dtype={"Codice Comune (alfanumerico)": str}))
situas_df = pd.concat(df_list, ignore_index=True)
situas_df.to_csv("situas_dataset.csv", index=False)
situas_df.sample(5)

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
30531,5,19,84,84,084020,84020,Lampedusa e Linosa,NaN,AG,0,0,6462,2021,"26,0976",2021,6462,2021
50544,2,5,24,24,024049,24049,Laghi,NaN,VI,0,0,120,2021,"22,2372",2024,125,2024
51210,2,8,34,34,034040,34040,Tornolo,NaN,PR,0,0,915,2021,"67,4780",2024,868,2024
30282,4,18,80,280,080083,80083,Santo Stefano in Aspromonte,NaN,RC,0,0,1091,2021,"17,7967",2021,1091,2021
30392,5,19,82,282,082071,82071,Terrasini,NaN,PA,0,0,12706,2021,"19,8453",2021,12706,2021